'use client';

import { useState, useEffect, useCallback } from 'react';
import Header from '@/components/Header';
import KPIStrip from '@/components/KPIStrip';
import PollingChart from '@/components/PollingChart';
import SentimentChart from '@/components/SentimentChart';
import IssueTracker from '@/components/IssueTracker';
import LiveFeed from '@/components/LiveFeed';
import CandidateCards from '@/components/CandidateCards';
import GeoSentiment from '@/components/GeoSentiment';
import { RedditPost, RedditComment, Tweet, Poll, SentimentData, FeedItem } from '@/lib/types';
import { mentionsChow, mentionsBradford, getItemSentiment } from '@/lib/sentiment';

const REFRESH_INTERVAL = 10 * 60 * 1000; // 10 minutes

interface PulseData {
  lastScraped: number;
  posts: RedditPost[];
  comments: RedditComment[];
  tweets: Tweet[];
  sentiment: SentimentData;
}

export default function Home() {
  const [posts, setPosts] = useState<RedditPost[]>([]);
  const [comments, setComments] = useState<RedditComment[]>([]);
  const [tweets, setTweets] = useState<Tweet[]>([]);
  const [polls, setPolls] = useState<Poll[]>([]);
  const [sentiment, setSentiment] = useState<SentimentData | null>(null);
  const [loading, setLoading] = useState(true);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [autoRefresh, setAutoRefresh] = useState(true);
  const [lastUpdated, setLastUpdated] = useState<number | null>(null);
  const [selectedIssue, setSelectedIssue] = useState<string | null>(null);
  const [dataError, setDataError] = useState(false);

  const fetchData = useCallback(async (isInitial = false) => {
    if (!isInitial) setIsRefreshing(true);

    try {
      // Fetch static pulse data (generated by scraper)
      const [pulseRes, pollsRes] = await Promise.allSettled([
        fetch(`/data/pulse-data.json?_=${Date.now()}`),
        fetch('/api/polls'),
      ]);

      if (pulseRes.status === 'fulfilled' && pulseRes.value.ok) {
        const data = await pulseRes.value.json();
        setPosts(data.posts || []);
        setComments(data.comments || []);
        setTweets(data.tweets || []);
        setSentiment(data.sentiment || null);
        setLastUpdated(data.lastScraped || Date.now());
        setDataError(false);
      } else {
        console.error('[TorontoPulse] Failed to load pulse data:', pulseRes.status === 'fulfilled' ? pulseRes.value.status : 'rejected');
        setDataError(true);
      }

      if (pollsRes.status === 'fulfilled' && pollsRes.value.ok) {
        const data = await pollsRes.value.json();
        setPolls(data.polls || []);
      }
    } catch (err) {
      console.error('Fetch error:', err);
      setDataError(true);
    } finally {
      setLoading(false);
      setIsRefreshing(false);
    }
  }, []);

  // Initial load
  useEffect(() => {
    fetchData(true);
  }, [fetchData]);

  // Auto-refresh
  useEffect(() => {
    if (!autoRefresh) return;
    const interval = setInterval(() => fetchData(), REFRESH_INTERVAL);
    return () => clearInterval(interval);
  }, [autoRefresh, fetchData]);

  // Build feed items from all sources
  const feedItems: FeedItem[] = [
    ...posts.map(p => ({
      type: 'post' as const,
      id: `post_${p.id}`,
      text: p.title,
      author: p.author,
      score: p.score,
      created_utc: p.created_utc,
      subreddit: p.subreddit,
      permalink: p.permalink,
      mentionsChow: mentionsChow(p.title + ' ' + p.selftext),
      mentionsBradford: mentionsBradford(p.title + ' ' + p.selftext),
      sentiment: getItemSentiment(p.title + ' ' + p.selftext),
      source: 'reddit' as const,
    })),
    ...comments.map(c => ({
      type: 'comment' as const,
      id: `comment_${c.id}`,
      text: c.body,
      author: c.author,
      score: c.score,
      created_utc: c.created_utc,
      subreddit: undefined,
      permalink: c.permalink,
      mentionsChow: mentionsChow(c.body),
      mentionsBradford: mentionsBradford(c.body),
      sentiment: getItemSentiment(c.body),
      source: 'reddit' as const,
    })),
    ...tweets.map(t => ({
      type: 'tweet' as const,
      id: t.id,
      text: t.text,
      author: t.handle,
      score: t.likes,
      created_utc: t.created_utc,
      subreddit: undefined,
      permalink: t.permalink,
      mentionsChow: mentionsChow(t.text),
      mentionsBradford: mentionsBradford(t.text),
      sentiment: getItemSentiment(t.text),
      source: 'twitter' as const,
    })),
  ].sort((a, b) => b.created_utc - a.created_utc);

  return (
    <div className="terminal-shell">
      <div className="app-grid">
        <aside className="side-nav">
          <div style={{ marginBottom: '26px' }}>
            <div style={{ fontSize: '28px', fontWeight: 800, color: '#f5f7fb', letterSpacing: '-0.05em' }}>TO Pulse 2026</div>
            <div style={{ fontSize: '13px', color: '#7b8494', marginTop: '6px' }}>Mayoral Race Terminal</div>
          </div>

          <nav style={{ display: 'grid', gap: '8px', marginBottom: '28px' }}>
            {[
              ['dashboard', 'Dashboard'],
              ['compare_arrows', 'Candidate Comparison'],
              ['analytics', 'Issue Tracker'],
              ['forum', 'Social Pulse'],
              ['map', 'Geographic Sentiment'],
            ].map(([icon, label], index) => (
              <div key={label} style={{
                display: 'flex', alignItems: 'center', gap: '12px', padding: '12px 14px', borderRadius: '14px',
                background: index === 0 ? 'rgba(255,255,255,0.06)' : 'transparent',
                border: `1px solid ${index === 0 ? 'rgba(255,255,255,0.08)' : 'transparent'}`,
                color: index === 0 ? '#f5f7fb' : '#97a1b2', fontSize: '14px', fontWeight: 600,
              }}>
                <span style={{ fontSize: '16px', opacity: 0.9 }}>{icon}</span>
                <span>{label}</span>
              </div>
            ))}
          </nav>

          <div className="surface-card" style={{ padding: '16px', marginBottom: '16px' }}>
            <div style={{ fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.08em', color: '#7b8494', marginBottom: '10px' }}>Live stream</div>
            <div style={{ fontSize: '32px', fontWeight: 800, color: '#f5f7fb', lineHeight: 1 }}>{feedItems.length}</div>
            <div style={{ fontSize: '13px', color: '#97a1b2', marginTop: '10px' }}>Signals across Reddit, X, and Bluesky</div>
          </div>

          <div className="surface-card" style={{ padding: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '10px' }}>
              <div style={{ fontSize: '13px', color: '#f5f7fb', fontWeight: 700 }}>Download Report</div>
              <div style={{ color: '#31d0aa', fontSize: '11px', fontWeight: 700 }}>LIVE</div>
            </div>
            <div style={{ fontSize: '12px', color: '#7b8494', lineHeight: 1.5 }}>Designed for a morning pulse check: see momentum, social chatter, and issue clusters before the day starts.</div>
          </div>
        </aside>

        <main style={{ padding: '28px', minWidth: 0 }}>
          <Header
            lastUpdated={lastUpdated}
            autoRefresh={autoRefresh}
            onToggleRefresh={() => setAutoRefresh(v => !v)}
            isRefreshing={isRefreshing}
          />

          {dataError && (
            <div style={{
              background: 'rgba(239, 68, 68, 0.1)',
              border: '1px solid rgba(239, 68, 68, 0.25)',
              borderRadius: '18px',
              padding: '12px 16px',
              marginBottom: '20px',
              fontSize: '12px',
              color: '#ff8d8d',
              fontWeight: 600,
            }}>
              Could not load pulse data — the scraper may not have run yet.
            </div>
          )}

          <KPIStrip sentiment={sentiment} loading={loading} />

          <div className="grid-main" style={{ marginBottom: '22px' }}>
            <div style={{ display: 'grid', gap: '20px', minWidth: 0 }}>
              <PollingChart polls={polls} loading={loading} />
              <div style={{ display: 'grid', gridTemplateColumns: '1.08fr 0.92fr', gap: '20px' }} className="two-up">
                <IssueTracker
                  sentiment={sentiment}
                  loading={loading}
                  onSelectIssue={setSelectedIssue}
                  selectedIssue={selectedIssue}
                />
                <SentimentChart sentiment={sentiment} loading={loading} />
              </div>
            </div>

            <div style={{ minWidth: 0 }}>
              <LiveFeed items={feedItems} loading={loading} issueFilter={selectedIssue} />
            </div>
          </div>

          <div style={{ display: 'grid', gap: '20px' }}>
            <CandidateCards sentiment={sentiment} loading={loading} />
            <GeoSentiment sentiment={sentiment} loading={loading} />
          </div>

          <footer style={{
            marginTop: '28px',
            paddingTop: '20px',
            borderTop: '1px solid rgba(123,132,148,0.14)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: '12px',
            flexWrap: 'wrap',
            color: '#667083',
            fontSize: '12px',
          }}>
            <div>Powered by Reddit, X API, and Bluesky • Sentiment analysis is keyword-based.</div>
            {lastUpdated && <div>Last scraped: {new Date(lastUpdated).toLocaleString('en-CA', { timeZone: 'America/Toronto' })} ET</div>}
          </footer>
        </main>
      </div>

      <style>{`
        @media (max-width: 1180px) {
          .two-up { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </div>
  );
}
